name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=node-version::$(<package.json jq -r '.engines.node' | sed 's/[^0-9.]*//g')"
        id: nvm

      - run: echo "::set-output name=pnpm-version::$(<package.json jq -r '.engines.pnpm' | sed 's/[^0-9.]*//g')"
        id: pnpm

      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys:
            - ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: ${{ steps.nvm.outputs.pnpm-version }}

      - uses: actions/setup-node@v2
        with:
          node-version: $node-version
          check-latest: false
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test

      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage

      - run: zip -r coverage.zip ./coverage

      - uses: actions/download-artifact@v2

      - run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

